# Generated by Django 3.0.6 on 2020-08-08 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Especilidad',
                'verbose_name_plural': 'Especilidades',
            },
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutritionist', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('license', models.CharField(max_length=100, verbose_name='cedula')),
                ('degree', models.CharField(max_length=100, verbose_name='titulo')),
                ('specialties', models.ManyToManyField(related_name='nutritionists', to='nutritionists.Specialty', verbose_name='especialidades')),
            ],
        ),
    ]
