# Generated by Django 3.0.6 on 2020-09-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
        ('patients', '0003_auto_20200908_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaltracing',
            name='meal_type',
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipes', to='patients.Patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_description', models.TextField(blank=True, null=True)),
                ('meal_type', models.CharField(blank=True, choices=[('Estandar', 'Estandar'), ('Perdida de Peso', 'Perdida de Peso'), ('Deportista', 'Deportista'), ('Vegano, Vegetariano', 'Vegano, Vegetariano'), ('Con Especificación', 'Con Especificación')], max_length=70, null=True)),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='nutritionists.Nutritionist', verbose_name='nutriolgo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='patients.Patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Plan Alimenticio',
                'verbose_name_plural': 'Planes Alimenticios',
            },
        ),
    ]
