# Generated by Django 3.0.6 on 2020-08-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
        ('patients', '0002_auto_20200808_0535'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritionists.Nutritionist', verbose_name='nutriolgo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritionists.Nutritionist', verbose_name='nutriolgo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='paciente'),
        ),
    ]
