# Generated by Django 3.0.6 on 2020-08-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200808_0522'),
        ('appointments', '0002_auto_20200808_0535'),
        ('appointments', '0002_auto_20200808_0350'),
        ('appointments', '0002_auto_20200808_0547'),
    ]

    operations = [
    ]
