# Generated by Django 3.0.6 on 2020-08-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200808_0345'),
        ('appointments', '0003_merge_20200808_0557'),
    ]

    operations = [
    ]
